# Generated by Django 6.0.4 on 2026-06-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Grande, Mediana, Sin Cebolla', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio específico si aplica', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'verbose_name': 'variante de producto',
                'verbose_name_plural': 'variantes de producto',
            },
        ),
    ]
