# Generated by Django 6.0.4 on 2026-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_foreign',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto original en moneda extranjera (USD). Null si se pagó en BOB.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar')], default='BOB', help_text='Moneda en que se recibió el pago (BOB o USD)', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de cambio USD→BOB usada al momento del cobro', max_digits=10, null=True),
        ),
    ]
